version: "3"

services:

  db:
    container_name: db
    image: postgres:13-alpine

    environment:
      - POSTGRES_USER=alexdenkk
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=db

    ports:
      - 5432:5432
    expose:
      - 5432

  users:
    container_name: users

    build:
      context: ../../users
      dockerfile: ../deployments/users/Dockerfile

    command: ./users -db-password=12345678

    ports:
      - 8001:8001

  books:
    container_name: books

    build:
      context: ../../books
      dockerfile: ../deployments/books/Dockerfile

    command: ./books -db-password=12345678

    ports:
      - 8002:8002

  reviews:
    container_name: reviews

    build:
      context: ../../reviews
      dockerfile: ../deployments/reviews/Dockerfile

    command: ./reviews -db-password=12345678

    ports:
      - 8003:8003

  genres:
    container_name: genres

    build:
      context: ../../genres
      dockerfile: ../deployments/genres/Dockerfile

    command: ./genres -db-password=12345678

    ports:
      - 8004:8004